# Step 1
FROM node:latest AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

RUN npm install -g @angular/cli

COPY . .

RUN npm run build:staging

# Step 2
FROM nginx:latest

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/ui-running-fund /usr/share/nginx/html

EXPOSE 80

# Build: docker build -t running-fund-ui-dev .
# Run: docker run -p 8080:80 running-fund-ui-dev